{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"GnustoEngine"}],"title":"ParseError.internalError(_:)","roleHeading":"Case","role":"symbol","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"]}],"abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"references":{"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"url":"\/documentation\/gnustoengine\/parseerror","kind":"symbol","navigatorTitle":[{"text":"ParseError","kind":"identifier"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","type":"topic","abstract":[{"text":"Enumerates errors that can occur during the command parsing phase.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParseError","kind":"identifier"}],"title":"ParseError"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","type":"topic","role":"symbol","kind":"symbol","title":"ParseError.internalError(_:)"},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","url":"\/documentation\/gnustoengine","abstract":[],"title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic","kind":"symbol"}}}