{"sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"variants":[{"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Case","modules":[{"name":"GnustoEngine"}],"externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","title":"ParseError.internalError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"case","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"url":"\/documentation\/gnustoengine","abstract":[],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","role":"collection","type":"topic","title":"GnustoEngine","kind":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"navigatorTitle":[{"text":"ParseError","kind":"identifier"}],"type":"topic","url":"\/documentation\/gnustoengine\/parseerror","role":"symbol","abstract":[{"type":"text","text":"Enumerates errors that can occur during the command parsing phase."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ParseError"}],"kind":"symbol","title":"ParseError","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"kind":"symbol","url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","role":"symbol","title":"ParseError.internalError(_:)","type":"topic","abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"}}}