{"metadata":{"role":"symbol","roleHeading":"Case","title":"ParseError.internalError(_:)","symbolKind":"case","modules":[{"name":"GnustoEngine"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)"},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"]}],"kind":"symbol","abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"title":"ParseError","role":"symbol","url":"\/documentation\/gnustoengine\/parseerror","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParseError","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enumerates errors that can occur during the command parsing phase."}],"navigatorTitle":[{"text":"ParseError","kind":"identifier"}]},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"title":"ParseError.internalError(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}]},"doc://GnustoEngine/documentation/GnustoEngine":{"abstract":[],"title":"GnustoEngine","role":"collection","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","url":"\/documentation\/gnustoengine","kind":"symbol","type":"topic"}}}