{"metadata":{"externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","modules":[{"name":"GnustoEngine"}],"symbolKind":"case","roleHeading":"Case","title":"ParseError.internalError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"]}],"abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","interfaceLanguage":"swift"},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"abstract":[{"type":"text","text":"Enumerates errors that can occur during the command parsing phase."}],"kind":"symbol","url":"\/documentation\/gnustoengine\/parseerror","title":"ParseError","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParseError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ParseError"}]},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"title":"ParseError.internalError(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","abstract":[{"type":"text","text":"An unexpected internal error occurred during parsing."}],"kind":"symbol","role":"symbol","url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"},"doc://GnustoEngine/documentation/GnustoEngine":{"url":"\/documentation\/gnustoengine","abstract":[],"kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic","title":"GnustoEngine","role":"collection"}}}