{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"]}],"abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError"]]},"kind":"symbol","identifier":{"url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"ParseError.internalError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Case","role":"symbol","externalID":"s:12GnustoEngine10ParseErrorO08internalD0yACSScACmF","modules":[{"name":"GnustoEngine"}]},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ParseError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ParseError","kind":"identifier"}],"title":"ParseError","type":"topic","role":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError","kind":"symbol","url":"\/documentation\/gnustoengine\/parseerror","navigatorTitle":[{"text":"ParseError","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumerates errors that can occur during the command parsing phase."}]},"doc://GnustoEngine/documentation/GnustoEngine":{"url":"\/documentation\/gnustoengine","role":"collection","abstract":[],"title":"GnustoEngine","kind":"symbol","type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine"},"doc://GnustoEngine/documentation/GnustoEngine/ParseError/internalError(_:)":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ParseError\/internalError(_:)","title":"ParseError.internalError(_:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"abstract":[{"text":"An unexpected internal error occurred during parsing.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/gnustoengine\/parseerror\/internalerror(_:)"}}}