{"sections":[],"kind":"symbol","abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"roleHeading":"Case","role":"symbol","title":"ActionResponse.internalEngineError(_:)","symbolKind":"case","modules":[{"name":"GnustoEngine"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF"},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"title":"ActionResponse","role":"symbol","navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}],"url":"\/documentation\/gnustoengine\/actionresponse","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}],"type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"title":"ActionResponse.internalEngineError(_:)","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"text":" provides details about the error, primarily for debugging.","type":"text"}]},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","title":"GnustoEngine","abstract":[],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","url":"\/documentation\/gnustoengine","type":"topic","kind":"symbol"}}}