{"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","modules":[{"name":"GnustoEngine"}],"symbolKind":"case","title":"ActionResponse.internalEngineError(_:)","roleHeading":"Case"},"identifier":{"url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"kind":"symbol","variants":[{"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"type":"topic","url":"\/documentation\/gnustoengine","abstract":[],"kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","title":"GnustoEngine","role":"collection"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}],"url":"\/documentation\/gnustoengine\/actionresponse","title":"ActionResponse","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionResponse"}],"role":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}]},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","type":"topic","abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"String"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"title":"ActionResponse.internalEngineError(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"}}}