{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"ActionResponse.internalEngineError(_:)","role":"symbol","roleHeading":"Case","externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","modules":[{"name":"GnustoEngine"}],"symbolKind":"case"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionResponse"}],"type":"topic","title":"ActionResponse","kind":"symbol","url":"\/documentation\/gnustoengine\/actionresponse","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}]},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"title":"ActionResponse.internalEngineError(_:)","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"},"doc://GnustoEngine/documentation/GnustoEngine":{"type":"topic","kind":"symbol","title":"GnustoEngine","role":"collection","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","abstract":[],"url":"\/documentation\/gnustoengine"}}}