{"kind":"symbol","metadata":{"symbolKind":"case","externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","modules":[{"name":"GnustoEngine"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"ActionResponse.internalEngineError(_:)","roleHeading":"Case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}]}],"abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"sections":[],"identifier":{"url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}],"title":"ActionResponse","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","abstract":[{"text":"Enumerates standard reasons why a game action might fail or be disallowed.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}],"url":"\/documentation\/gnustoengine\/actionresponse"},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","type":"topic","url":"\/documentation\/gnustoengine","abstract":[],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","title":"GnustoEngine","kind":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","type":"topic","title":"ActionResponse.internalEngineError(_:)","kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol"}}}