{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"GnustoEngine"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"case","title":"ActionResponse.internalEngineError(_:)"},"sections":[],"references":{"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"role":"symbol","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","title":"ActionResponse.internalEngineError(_:)","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"kind":"symbol","abstract":[{"text":"Enumerates standard reasons why a game action might fail or be disallowed.","type":"text"}],"title":"ActionResponse","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","type":"topic","url":"\/documentation\/gnustoengine\/actionresponse","navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}],"role":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine":{"role":"collection","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","kind":"symbol","title":"GnustoEngine","abstract":[],"url":"\/documentation\/gnustoengine","type":"topic"}}}