{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"GnustoEngine"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","symbolKind":"case","role":"symbol","title":"ActionResponse.internalEngineError(_:)"},"sections":[],"abstract":[{"type":"text","text":"An unexpected internal error occurred within the engine or an action handler."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["macOS"]}]}],"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"url":"\/documentation\/gnustoengine","role":"collection","abstract":[],"title":"GnustoEngine","kind":"symbol","type":"topic","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the engine or an action handler."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","title":"ActionResponse.internalEngineError(_:)"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"title":"ActionResponse","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}],"identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","type":"topic","url":"\/documentation\/gnustoengine\/actionresponse","abstract":[{"type":"text","text":"Enumerates errors that can occur during the execution phase of a command."}]}}}