{"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"String","type":"codeVoice"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"metadata":{"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","role":"symbol","title":"ActionResponse.internalEngineError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"GnustoEngine"}],"symbolKind":"case","roleHeading":"Case"},"sections":[],"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"title":"GnustoEngine","role":"collection","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/gnustoengine"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"title":"ActionResponse.internalEngineError(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"kind":"symbol"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"role":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","title":"ActionResponse","url":"\/documentation\/gnustoengine\/actionresponse","kind":"symbol","abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}],"type":"topic"}}}