{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"]}],"metadata":{"symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalEngineError"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","modules":[{"name":"GnustoEngine"}],"title":"ActionResponse.internalEngineError(_:)"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the engine or an action handler."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/gnustoengine","abstract":[]},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"role":"symbol","type":"topic","kind":"symbol","title":"ActionResponse.internalEngineError(_:)","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","abstract":[{"text":"An unexpected internal error occurred within the engine or an action handler.","type":"text"}],"url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"internalEngineError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"url":"\/documentation\/gnustoengine\/actionresponse","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","abstract":[{"type":"text","text":"Enumerates errors that can occur during the execution phase of a command."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionResponse"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActionResponse","kind":"identifier"}],"role":"symbol","title":"ActionResponse"}}}