{"variants":[{"paths":["\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"GnustoEngine"}],"title":"ActionResponse.internalEngineError(_:)","externalID":"s:12GnustoEngine14ActionResponseO08internalB5ErroryACSScACmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"kind":"symbol","abstract":[{"type":"text","text":"An unexpected internal error occurred within the game engine or an action handler."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"text":" provides details about the error, primarily for debugging.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/GnustoEngine\/documentation\/GnustoEngine","doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalEngineError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://GnustoEngine/documentation/GnustoEngine":{"title":"GnustoEngine","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine","kind":"symbol","type":"topic","url":"\/documentation\/gnustoengine","abstract":[],"role":"collection"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse/internalEngineError(_:)":{"role":"symbol","url":"\/documentation\/gnustoengine\/actionresponse\/internalengineerror(_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalEngineError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"abstract":[{"text":"An unexpected internal error occurred within the game engine or an action handler.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" provides details about the error, primarily for debugging."}],"kind":"symbol","title":"ActionResponse.internalEngineError(_:)","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse\/internalEngineError(_:)","type":"topic"},"doc://GnustoEngine/documentation/GnustoEngine/ActionResponse":{"kind":"symbol","identifier":"doc:\/\/GnustoEngine\/documentation\/GnustoEngine\/ActionResponse","role":"symbol","navigatorTitle":[{"text":"ActionResponse","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionResponse","kind":"identifier"}],"abstract":[{"type":"text","text":"Enumerates standard reasons why a game action might fail or be disallowed."}],"type":"topic","url":"\/documentation\/gnustoengine\/actionresponse","title":"ActionResponse"}}}